services:

  mysql:
    image: mysql:8.4
    container_name: ocorrencias-mysql

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - ocorrencias-network

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    image: ocorrencias-backend:test
    restart: on-failure
    container_name: ocorrencias-backend

    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - ocorrencias-network


  frontend:
    image: ocorrencias-frontend:test
    container_name: ocorrencias-frontend

    ports:
      - "8082:80"

    depends_on:
      backend:
        condition: service_started

    networks:
      - ocorrencias-network


volumes:
  mysql_data:


networks:
  ocorrencias-network: